services:
  gitlab:
    image: gitlab/gitlab-ce:17.0.6-ce.0
    container_name: gitlab
    hostname: 'git.anakdevops.online'  # Use a placeholder domain
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.anakdevops.online'  # Set the external URL without HTTPS
        gitlab_rails['gitlab_shell_ssh_port'] = 223
    ports:
      - '8080:80'  # Expose GitLab on port 80
      - '223:22'  # SSH port
    volumes:
      - ./config-gitlab:/etc/gitlab
      - ./logs-gitlab:/var/log/gitlab
      - ./data-gitlab:/var/opt/gitlab
